apiVersion: http.crossplane.io/v1alpha1
kind: DisposableRequest
metadata:
  name: health-check
spec:
  secretsRefs:
    - name: secretname
      namespace: crossplane-system
      fieldPath: token
      toFieldPaths: 
        - forProvider.headers.authorization[0]
  deletionPolicy: Orphan
  forProvider:
    # The 'expectedResponse' field is optional. If used, also set 'rollbackRetriesLimit', which determines the number of HTTP requests to be sent until the jq query returns true.    
    # expectedResponse: '.Body.job_status == "success"'
    insecureSkipTLSVerify: true
    waitTimeout: 5m
    rollbackRetriesLimit: 5
    url:  http://todo.default.svc.cluster.local/health-check
    method: POST
    body: |
      {
        "check_type": "simple",
        "additional_info": "optional"
      }
    headers:
      User-Agent: 
        - "Crossplane Health Checker"
  providerConfigRef:
    name: http-conf
# TODO: check if it's possible to modify the deletionPolicy to be orphan by default.
