apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example
  labels: 
    crossplane.io/xrd: xdemos.releases.example.io
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: releases.example.io/v1alpha1
    kind: XDemo
  resources:
  - name: demo
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      spec:
        forProvider:
          chart:
            name: wordpress
            repository: https://charts.bitnami.com/bitnami
          namespace: wordpress
    patches:
      - fromFieldPath: spec.wordpressVersion
        toFieldPath: spec.forProvider.chart.version
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.state
        toFieldPath: status.helm.state
        policy:
          fromFieldPath: Optional
  - name: httprequest
    base:
      apiVersion: http.crossplane.io/v1alpha2
      kind: DisposableRequest 
      spec:
          deletionPolicy: Orphan
          forProvider:
            url: https://enwgarmh79yh.x.pipedream.net/
            method: POST
            body: '{"key1": "value1"}'
            headers:
              Authorization:
                - Just a Token
              Custom-Header:
                - Nice Header
                - Value2
                - Value3
          providerConfigRef:
            name: http-conf
          rollbackLimit: 2
    patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.response.body
        toFieldPath: status.http.response.body
        transforms:
          - type: convert
            convert:
              toType: object
              format: json