name: Promote

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.0.1)"
        required: true
      channel:
        description: "Release channel"
        required: true
        default: "alpha"

env:
  CONTRIB_DOCKER_USR: ${{ secrets.CONTRIB_DOCKER_USR }}

jobs:
  promote-artifacts:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Login to Docker
        uses: docker/login-action@v1
        if: env.CONTRIB_DOCKER_USR != ''
        with:
          username: ${{ secrets.CONTRIB_DOCKER_USR }}
          password: ${{ secrets.CONTRIB_DOCKER_PSW }}

      - name: Promote Artifacts in S3 and Docker Hub
        if: env.CONTRIB_DOCKER_USR != ''
        run: make -j2 promote BRANCH_NAME=${GITHUB_REF##*/}
        env:
          VERSION: ${{ github.event.inputs.version }}
          CHANNEL: ${{ github.event.inputs.channel }}
